import { v4 as uuidv4 } from 'uuid';
const vehicles = [
    // Ford Focus Sedan
    {
        brand: 'Ford',
        model: 'Focus Sedan',
        version: '2.0 Titanium Plus 16V Flex 4p Aut.',
        year: 2016,
        specs: {
            engine: '2.0 16V Duratec Flex',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Eletrônica multiponto',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '178 cv (etanol) / 175 cv (gasolina)',
            torque: '22,5 kgfm (etanol) / 22,0 kgfm (gasolina)',
            displacement: '1999 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'Automático de 6 marchas',
            maxSpeedKmH: 210,
            acceleration0to100: '9,2 s',
            consumptionCity: '6,4 km/l (etanol)',
            consumptionHighway: '9,2 km/l (etanol)',
            frontSuspension: 'Independente tipo McPherson',
            rearSuspension: 'Independente tipo Multilink',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 17"',
            tires: '215/50 R17',
            lengthMM: 4534,
            wheelbaseMM: 2648,
            heightMM: 1497,
            widthMM: 1823,
            curbWeightKg: 1320,
            trunkCapacityL: 421,
            tankCapacityL: 55,
            payloadKg: 425,
            doors: 4,
            seats: 5,
        },
    },
    // Chevrolet Cruze
    {
        brand: 'Chevrolet',
        model: 'Cruze',
        version: 'LTZ 1.4 Turbo Flex 16V Aut.',
        year: 2017,
        specs: {
            engine: '1.4 Ecotec Turbo Flex',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Direta',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '153 cv (etanol) / 150 cv (gasolina)',
            torque: '24,5 kgfm (etanol) / 24 kgfm (gasolina)',
            displacement: '1399 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'Automático de 6 marchas',
            maxSpeedKmH: 214,
            acceleration0to100: '8,8 s',
            consumptionCity: '7,8 km/l (etanol)',
            consumptionHighway: '9,6 km/l (etanol)',
            frontSuspension: 'McPherson independente',
            rearSuspension: 'Eixo de torção',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 17"',
            tires: '215/50 R17',
            lengthMM: 4666,
            wheelbaseMM: 2700,
            heightMM: 1484,
            widthMM: 1791,
            curbWeightKg: 1288,
            trunkCapacityL: 440,
            tankCapacityL: 52,
            payloadKg: 420,
            doors: 4,
            seats: 5,
        },
    },
    // Hyundai Elantra
    {
        brand: 'Hyundai',
        model: 'Elantra',
        version: 'GLS 2.0 Flex Aut.',
        year: 2018,
        specs: {
            engine: '2.0 16V Flex',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Multiponto',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '167 cv (etanol) / 157 cv (gasolina)',
            torque: '20,6 kgfm (etanol) / 19,6 kgfm (gasolina)',
            displacement: '1999 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'Automático de 6 marchas',
            maxSpeedKmH: 203,
            acceleration0to100: '9,9 s',
            consumptionCity: '6,9 km/l (etanol)',
            consumptionHighway: '9,1 km/l (etanol)',
            frontSuspension: 'McPherson independente',
            rearSuspension: 'Eixo de torção',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 17"',
            tires: '215/45 R17',
            lengthMM: 4570,
            wheelbaseMM: 2700,
            heightMM: 1450,
            widthMM: 1800,
            curbWeightKg: 1270,
            trunkCapacityL: 458,
            tankCapacityL: 50,
            payloadKg: 425,
            doors: 4,
            seats: 5,
        },
    },
    // Toyota Corolla
    {
        brand: 'Toyota',
        model: 'Corolla',
        version: 'Altis 2.0 Flex 16V Aut.',
        year: 2019,
        specs: {
            engine: '2.0 Dual VVT-i Flex',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Multiponto',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '154 cv (etanol) / 143 cv (gasolina)',
            torque: '20,7 kgfm (etanol) / 19,4 kgfm (gasolina)',
            displacement: '1987 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'CVT',
            maxSpeedKmH: 199,
            acceleration0to100: '9,5 s',
            consumptionCity: '7,2 km/l (etanol)',
            consumptionHighway: '8,8 km/l (etanol)',
            frontSuspension: 'McPherson independente',
            rearSuspension: 'Eixo de torção',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 17"',
            tires: '215/50 R17',
            lengthMM: 4630,
            wheelbaseMM: 2700,
            heightMM: 1460,
            widthMM: 1780,
            curbWeightKg: 1295,
            trunkCapacityL: 470,
            tankCapacityL: 55,
            payloadKg: 430,
            doors: 4,
            seats: 5,
        },
    },
    // Volkswagen Jetta
    {
        brand: 'Volkswagen',
        model: 'Jetta',
        version: 'Comfortline 1.4 TSI Flex 16V Aut.',
        year: 2019,
        specs: {
            engine: '1.4 TSI Flex',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Direta',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '150 cv (etanol/gasolina)',
            torque: '25,5 kgfm',
            displacement: '1395 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'Automático de 6 marchas',
            maxSpeedKmH: 203,
            acceleration0to100: '8,9 s',
            consumptionCity: '7,0 km/l (etanol)',
            consumptionHighway: '9,6 km/l (etanol)',
            frontSuspension: 'McPherson independente',
            rearSuspension: 'Multilink independente',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 16"',
            tires: '205/55 R16',
            lengthMM: 4702,
            wheelbaseMM: 2651,
            heightMM: 1473,
            widthMM: 1799,
            curbWeightKg: 1280,
            trunkCapacityL: 510,
            tankCapacityL: 55,
            payloadKg: 445,
            doors: 4,
            seats: 5,
        },
    },
    // Nissan Sentra
    {
        brand: 'Nissan',
        model: 'Sentra',
        version: 'SL 2.0 FlexStart 16V Aut.',
        year: 2018,
        specs: {
            engine: '2.0 16V FlexStart',
            engineLayout: '4 cilindros em linha',
            valves: '16',
            fuelInjection: 'Multiponto',
            enginePosition: 'Dianteiro',
            fuelType: 'Flex',
            power: '140 cv (etanol/gasolina)',
            torque: '20,0 kgfm',
            displacement: '1997 cm³',
            steering: 'Elétrica',
            drivetrain: 'Dianteira',
            transmission: 'CVT',
            maxSpeedKmH: 190,
            acceleration0to100: '10,0 s',
            consumptionCity: '6,9 km/l (etanol)',
            consumptionHighway: '9,5 km/l (etanol)',
            frontSuspension: 'McPherson independente',
            rearSuspension: 'Eixo de torção',
            frontBrakes: 'Disco ventilado',
            rearBrakes: 'Disco sólido',
            wheels: 'Liga leve 17"',
            tires: '205/50 R17',
            lengthMM: 4635,
            wheelbaseMM: 2700,
            heightMM: 1500,
            widthMM: 1760,
            curbWeightKg: 1292,
            trunkCapacityL: 503,
            tankCapacityL: 52,
            payloadKg: 435,
            doors: 4,
            seats: 5,
        },
    },
];

export async function seedVehicleModels(sequelize: any) {
    const now = new Date();

    for (const v of vehicles) {
        const vehicleId = uuidv4();
        const label = `${v.brand}_${v.model}_${v.version}_${v.year}`;

        await sequelize.models.VehicleModel.create({
            id: vehicleId,
            brand: v.brand,
            model: v.model,
            version: v.version,
            year: v.year,
            label,
            createdAt: now,
            updatedAt: now,
            deletedAt: null,
        });

        await sequelize.models.VehicleSpecModel.create({
            id: uuidv4(),
            vehicleId,
            ...v.specs,
            createdAt: now,
            updatedAt: now,
            deletedAt: null,
        });
    }

    console.log('🚗 Seed de veículos inseridos com sucesso!');
}
